name: 'github issue automation'
description: 'Run checks within github issues'
author: 'joshcarp'
inputs:
  gh_token:
    description: 'repo access token'
    required: true
  gh_owner:
    description: 'repo owner'
    required: true
  gh_repo:
    description: 'repo'
    required: true
runs:
  using: 'docker'
  image: 'docker://gcr.io/joshcarp/gh-issue-automation:latest'
branding:
  icon: 'pie-chart'
  color: 'gray-dark'
