name: 'github issue automation'
description: 'Run checks within github issues'
author: 'joshcarp'
inputs:
  repository:
    description: 'Repository name with owner. For example, joshcarp/predicate'
    default: ${{ github.repository }}
    required: false
  token:
    description: >
      Personal access token (PAT) used to fetch the repository. The PAT is configured
      with the local git config, which enables your scripts to run authenticated git
      commands. The post-job step removes the PAT.
      We recommend using a service account with the least permissions necessary.
      Also when generating a new PAT, select the least scopes necessary.
      [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
    default: ${{ github.token }}
    required: false
runs:
  using: 'docker'
  image: 'docker://gcr.io/joshcarp/predicate:latest'
branding:
  icon: 'pie-chart'
  color: 'gray-dark'
