name: deploy

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get version
        id: get_version
        run: |
          echo ::set-output name=version::${GITHUB_REF#refs/*/}
      - name: Setup - gcloud / gsutil
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          export_default_credentials: true
          project_id: joshcarp
      - name: gcloud
        run: gcloud auth configure-docker
      - name: Build and push docker image
        run: |
          docker build . -t dockerimage
          docker tag dockerimage gcr.io/joshcarp/predicate:latest
          docker push gcr.io/joshcarp/predicate:latest
          docker tag dockerimage gcr.io/joshcarp/predicate:${{ steps.get_version.outputs.version }}
          docker push gcr.io/joshcarp/predicate:${{ steps.get_version.outputs.version }}
