name: bump version
on:
  issues:
    types: [opened, edited, milestoned]
  schedule:
    - cron:  '* * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: foobar
        run: |
          env
          cat /home/runner/work/_temp/_github_workflow/event.json
